spring:
  application:
    name: ecommerce_aryanjakhar

  data:
    mongodb:
      uri: mongodb+srv://aryan24bcs10305_db_user:in34ow6ANrRJaSFj@cluster0.qy09zxv.mongodb.net/?appName=Cluster0

server:
  port: 8080
